package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

const generatedFileName = "reset.gen.go"

var projectRootPath string

func main() {
	//  1. Get root path of project
	projectRootPath = findRootPath()

	// 2. get go package and types info
	pkgs, err := getGoPackages(projectRootPath)
	if err != nil {
		log.Fatal(err)
	}

	// 3. parse go files from packages and generate reset files
	err = parseGoFilesFromPackages(pkgs)
	if err != nil {
		log.Fatal(err)
	}
}

func getGoPackages(dir string) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedImports,
		Dir: dir,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, fmt.Errorf("error occurred during getting go packages from project: %w", err)
	}

	return pkgs, nil
}

func generateResetMethods(out *bytes.Buffer, file *ast.File, pkg *packages.Package) error {
	for _, declaration := range file.Decls {
		genericDeclaration, ok := declaration.(*ast.GenDecl)

		// check if it is a type declaration
		if !ok || genericDeclaration.Tok != token.TYPE {
			continue // not a type declaration
		}

		// check if Doc not nil and has `generate` comment
		if !hasDeclarationGenerateComments(genericDeclaration) {
			continue
		}

		// for every type with generate comment
		for _, specification := range genericDeclaration.Specs {
			typeSpecification := specification.(*ast.TypeSpec)
			// check if a declaration of type is struct type declaration
			structType, ok := typeSpecification.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// generate reset method
			generateResetMethod(out, typeSpecification, structType, pkg.TypesInfo)
		}
	}

	return nil
}

func parseGoFilesFromPackages(pkgs []*packages.Package) error {
	var out bytes.Buffer // buffer for writing to files

	// for every package
	for _, pkg := range pkgs {

		// for every file in package
		for _, file := range pkg.Syntax {
			// check if file doesn't have `generate:reset` comments
			if !hasFileGenerateResetComments(file) {
				continue // go to the next file
			}

			// check if we are at the start of generating file
			if out.Len() == 0 {
				out.WriteString("// Code generated by reset-generator. DO NOT EDIT.\n\n")
				out.WriteString("package " + pkg.Types.Name() + "\n\n")
			}

			// generate reset method and append it to the out buffer
			err := generateResetMethods(&out, file, pkg)
			if err != nil {
				return fmt.Errorf("error during generating reset method: %w", err)
			}
		}

		// check if no reset methods were generated
		if out.Len() == 0 {
			continue // go the next package
		}

		// format generated generated go file
		bufFmt, err := format.Source(out.Bytes())
		if err != nil {
			return fmt.Errorf("error occured during formatting generated code: %w", err)
		}

		// write formatted source file to file
		generatedFileForPackage := filepath.Join(pkg.Dir, generatedFileName)
		if err := os.WriteFile(generatedFileForPackage, bufFmt, 0644); err != nil {
			return fmt.Errorf("error occured saving generated code to file `%s`: %w", generatedFileForPackage, err)
		}

		out.Reset()
	}

	return nil
}
